name = "useuxray"
main = "apps/cloudflare/src/index.ts"
compatibility_date = "2026-07-05"

routes = [
  { pattern = "useuxray.com", custom_domain = true },
  { pattern = "www.useuxray.com", custom_domain = true }
]

[assets]
directory = "./apps/site"
binding = "ASSETS"

[vars]
RENDER_API_BASE = "https://uxray-renderer.fly.dev"

[[d1_databases]]
binding = "DB"
database_name = "uxray-reports"
database_id = "2badb4fb-943f-4b8d-b835-85c284b51702"

[[r2_buckets]]
binding = "REPORTS"
bucket_name = "uxray-reports"
